### ISSUE TITLE
Make it Possible for the Same Recipient to Have Two Tags of the Same Type

### ISSUE THREAD

**Issue by Gauntlet173** [radiant-law/docassemble-docusign#5]
Right now, if the same recipient needs to sign the document in two different places, that will result in two identical anchor texts, which seems like on its face might not work properly. We can refactor to make it a list of tags, each with a unique anchor text.

**Comment by linky00** [comment]
I think it would work properly! Check this out: https://developers.docusign.com/esign-rest-api/guides/concepts/tabs#data-replication

**Comment by Gauntlet173** [comment]
I think you're right. Closing the issue.
